-- ============================================================
-- Seed : vocabulaire de compétences réalistes (table tags)
-- ------------------------------------------------------------
-- Rend les suggestions métiers (langage naturel) immédiatement
-- disponibles dans l’autocomplete du Portefeuille et la recherche
-- de l’annuaire, sans attendre la saisie organique des utilisateurs.
-- Les noms sont en minuscules (normalisation appliquée par l’app).
-- ============================================================

INSERT INTO public.tags (name) VALUES
  ('accueil & réception'),
  ('agent de sécurité événementiel'),
  ('aide aux devoirs'),
  ('aide aux devoirs / cours à domicile'),
  ('animation & maître de cérémonie'),
  ('animation musicale (dj)'),
  ('animation radio / tv'),
  ('animation touristique'),
  ('approvisionnement & achats'),
  ('approvisionnement en matériel'),
  ('arbitrage sportif'),
  ('assurance auto & habitation'),
  ('audit de conformité'),
  ('boutique & magasin'),
  ('climatisation & froid'),
  ('coach remise en forme'),
  ('coach sportif personnel'),
  ('coaching et développement d''affaires'),
  ('coiffure homme / barbe'),
  ('communication'),
  ('conception de menus de restaurant'),
  ('conditionnement & emballage'),
  ('conseil'),
  ('conseil en agriculture'),
  ('conseil en gestion d''argent'),
  ('conseil en nutrition'),
  ('conseil fiscal'),
  ('conseil pour création d''entreprise'),
  ('consultation médicale'),
  ('consulting d''entreprise'),
  ('coudre un bomba / tenue traditionnelle'),
  ('coudre un corset'),
  ('coudre une chemise / pantalon'),
  ('coudre une robe de mariée'),
  ('cours de danse'),
  ('cours de fitness / musculation'),
  ('cours de football'),
  ('cours de langues (anglais, français)'),
  ('cours de musique'),
  ('cours à domicile / répétiteur'),
  ('coursier moto'),
  ('courtage immobilier'),
  ('couverture photo/vidéo d''événement'),
  ('création de logo & flyers'),
  ('création de visuels / canva'),
  ('créer un site web'),
  ('créer une application mobile'),
  ('cuisine de plats locaux (jollof, garba, yassa)'),
  ('distribution de produits'),
  ('déclaration d''impôts'),
  ('décoration & peinture artistique'),
  ('décoration de salle'),
  ('dédouanement'),
  ('défense au tribunal'),
  ('démarches d''enregistrement foncier'),
  ('démarches foncières'),
  ('déménagement'),
  ('dépannage d''appareils électroménagers'),
  ('encadrement scolaire'),
  ('estimation de bien'),
  ('fabrication de jus locaux et cocktails'),
  ('fabrication métallique'),
  ('faire du staff / plâtre décoratif'),
  ('formation'),
  ('formation en informatique'),
  ('formation professionnelle'),
  ('fourniture aux entreprises'),
  ('froid & climatisation'),
  ('gardiennage de nuit'),
  ('gestion administrative'),
  ('gestion d''immeuble / syndic'),
  ('gestion de budget d''entreprise'),
  ('gestion de cuisine & service en salle'),
  ('gestion de page facebook / instagram'),
  ('gestion de projet'),
  ('gestion de réseaux sociaux'),
  ('gestion des déchets / recyclage'),
  ('gestion locative (loyers)'),
  ('groupe électrogène (vente / entretien)'),
  ('guide touristique'),
  ('illustration & dessin'),
  ('import-export de marchandises'),
  ('infographie & création de logo'),
  ('installation d''antennes tv / canal+'),
  ('installation de caméras de surveillance'),
  ('installation de panneaux solaires'),
  ('installation électrique'),
  ('installation électrique de maison'),
  ('jardinage & aménagement de cour'),
  ('lavage et entretien de voiture'),
  ('livraison'),
  ('livraison de colis'),
  ('livraison de commandes'),
  ('location d''appartements'),
  ('location de chaises / bâches'),
  ('location de matériel de fête'),
  ('location de vacances'),
  ('location de véhicules'),
  ('logiciel de comptabilité'),
  ('logistique & stockage'),
  ('maintenance de machines'),
  ('maintenance informatique entreprise'),
  ('maintenance énergétique'),
  ('manucure & onglerie'),
  ('maquillage professionnel / make-up'),
  ('massage & kiné'),
  ('maçonnerie & gros œuvre'),
  ('montage de dossier de crédit'),
  ('montage vidéo & clip'),
  ('montage vidéo pour réseaux sociaux'),
  ('nettoyage de bureaux & résidences'),
  ('organisation d''événements'),
  ('organisation de mariage'),
  ('organisation de tournois'),
  ('organisation de voyages'),
  ('peindre des bâtiments'),
  ('photographe / vidéaste d''événement'),
  ('photographie d''événements (mariage, baptême)'),
  ('pisciculture / élevage de poissons'),
  ('plans de maison & plan d''architecte'),
  ('plomberie & forage'),
  ('plomberie & réparation de fuites'),
  ('poser du carrelage / pavés'),
  ('prestation de services aux sociétés'),
  ('production d''œufs / aviculture'),
  ('production maraîchère (légumes)'),
  ('prospection commerciale'),
  ('protection rapprochée'),
  ('préparation aux examens (bac, bepc)'),
  ('préparation physique'),
  ('publicité & affichage'),
  ('publicité facebook & instagram'),
  ('pâtisserie & gâteaux d''anniversaire'),
  ('recherche de logement'),
  ('recrutement de personnel'),
  ('relations presse & communiqué'),
  ('reportage & journalisme'),
  ('restauration & bar'),
  ('rondes & patrouilles'),
  ('règlement de litiges'),
  ('rédaction d''articles'),
  ('rédaction web (référencement)'),
  ('rédiger un contrat de travail'),
  ('réparation d''engins'),
  ('réparation de moteur / mécanique auto'),
  ('réparer un ordinateur / maintenance'),
  ('réservation d''hôtel'),
  ('secourisme & premiers soins'),
  ('service client'),
  ('soins infirmiers à domicile'),
  ('sonorisation & lumière (dj)'),
  ('soudure & fabrication de portails'),
  ('soudure & métallerie'),
  ('sous-traitance'),
  ('soutien et conseil en ressources humaines'),
  ('soutien psychologique'),
  ('stylisme et création de modèles'),
  ('suivi de grossesse'),
  ('sécurité et gardiennage de nuit'),
  ('sécurité incendie'),
  ('sérigraphie & impression t-shirt'),
  ('tenue de comptabilité'),
  ('traiteur pour événements (mariage, baptême)'),
  ('traiteur événementiel'),
  ('transfert d''argent / mobile money'),
  ('transformation de produits (jus, farine)'),
  ('transport de marchandises'),
  ('transport de personnes (taxi, vtc)'),
  ('transport de touristes'),
  ('tresses & coiffure femme'),
  ('télésurveillance'),
  ('tôlerie & peinture auto'),
  ('vente & commerce'),
  ('vente de médicaments / pharmacie'),
  ('vente de produits agricoles'),
  ('vente de terrain & maison'),
  ('vente de vêtements / friperie'),
  ('vente en gros et détail'),
  ('vente en ligne (whatsapp / facebook)'),
  ('yoga & relaxation'),
  ('éclairage solaire'),
  ('électricité industrielle'),
  ('élevage (poulets, porcs)'),
  ('établir un bilan comptable')
ON CONFLICT (name) DO NOTHING;
